version: "3.8"

services:
  kener:
    image: andrecostabr/kener:main        
    environment:
      - TZ=${TZ}
      - KENER_SECRET_KEY=${KENER_SECRET_KEY} # 🔐 API key / secret
      - DATABASE_URL=${DATABASE_URL}
      - KENER_BASE_PATH=${KENER_BASE_PATH}
      - ORIGIN=${ORIGIN}
      - RESEND_API_KEY=${RESEND_API_KEY} # 🔐 API key
      - RESEND_SENDER_EMAIL=${RESEND_SENDER_EMAIL}
      - REDIS_URL=redis://kener-redis:6379 # Conecta automaticamente ao serviço do Redis abaixo
    ports:
      - 3000
    volumes:
      - kener_db:/app/database
      - ../files/uploads:/app/uploads
    restart: unless-stopped
   
  kener-redis:
    image: redis:alpine
    volumes:
      - kener_redis_data:/data # Mantém os dados da fila salvos
    restart: unless-stopped

volumes:
  kener_db: {}
  kener_redis_data: {}